### ISSUE TITLE
Not 100% of aristocrats convert at the moment of EU4 conversion

### ISSUE THREAD

**Issue by oliverzzt** [ParadoxGameConverters/EU4ToVic2#1000]
"At the moment of EU4 conversion 100% of aristocrats and 50% of middle strata convert."

I've already converted cultures of colonies and territories conquered to my own culture in eu4, but no province has its 100% of aristocrats converted in vic2.

**Comment by Zemurin** [comment]
Please go to forums, upload affected eu4 save and conversion's log.txt. Some screenshots of the issue would also be helpful.
These github issues are for internal tracking mostly.
