### ISSUE TITLE
Provinces of Korean culture didn't receive a core of Korea

### ISSUE THREAD

**Issue by oliverzzt** [ParadoxGameConverters/EU4ToVic2#1001]
In eu4, I played as another country and annexed Korea. Provinces of korean culture didn't receive a core of Korea in vic2.

**Comment by Zemurin** [comment]
Please go to forums, upload affected eu4 save and conversion's log.txt. Some screenshots of the issue would also be helpful.
These github issues are for internal tracking mostly.
