### ISSUE TITLE
Read province list from mod file if needed

### ISSUE THREAD

**Issue by kratostatic** [ParadoxGameConverters/EU4toVic2#101]
Possibly could be generalised to "read anything from the mod file if it replaces the original depending on how I code it exactly.  Needed for any mod which has province ids which differ from vanilla.

**Comment by Zemurin** [comment]
We've never been able to support anything other than vanilla eu4 maps.
Main issue is the province mappings.
but also, eu4 gives us crucial area.txt, regions.txt and superregions.txt that we need for a lot of stuff
none of culture mappers work without a positive link between vanilla areas.txt and province IDs
I suppose you could change that and we could use alternative sources, but without a replacement province_mappings.txt it's all moot.
Does this issue even need to exist any more?
Chances of us supporting beyond typus are slim to nil.
