### ISSUE TITLE
Convert Canals

### ISSUE THREAD

**Issue by Idhrendur** [ParadoxGameConverters/EU4toVic2#11]
DasGuntLord01 figured out how to put them in Vic2: http://forum.paradoxplaza.com/forum/showthread.php?707362-The-EU4-to-V2-Converter-Project&p=18921501&viewfull=1#post18921501

**Comment by IhateTrains** [comment]
It seems they aren't converted in a 1.28.3 save, probably because the way they are saved has changed.

**Comment by IhateTrains** [comment]
I get this warning:

> Unknown token while parsing stream: "suez_canal"

**Comment by Idhrendur** [comment]
Ah, that means you'll need to add a new rule to whatever class is reading at the point that error appears. I find it easiest to put a breakpoint at the line that outputs 'Unknown token while parsing stream'  to see where that is.

**Comment by IhateTrains** [comment]
The issue can be closed.
