### ISSUE TITLE
Conditions for determining a colony state

### ISSUE THREAD

**Issue by TheAtom** [ParadoxGameConverters/EU4toVic2#116]
This concerns "colony" vs. "state" status of a V2 state. Presently, a converted state is turned into a colony if it meets all of the below:
1) it is not on the same continent as the capital,
2) it is not connected by land,
3) it was colonized or "infidel-conquered".

It is converted into a state otherwise.

"Infidel-conquered" means that any (EU4) province in the state satisfies:
a) the province's original religion is considered heathen by the current owner's religion, **AND**
b) the province's original culture is different from its current culture.

This means that the state will not be turned into a colony if its provinces' cultures remain original. If the conqueror converts one of those provinces to other culture (i.e. it's own), the state will become a colony.

Additionaly, the code doesn't seem to care about the original "territory" vs. "state" status of the EU4 states that the provinces belong to.

Proposed solution: replace b) with "b') the province's original culture is not an accepted culture by the province's current owner".

Note that normally in order to elevate a culture to an accepted status, some state of this culture must be first elevated to "state" from "territory".

It would also be nice to somehow force all overseas, unconnected territories to be converted to colonies no matter what. The problem is obviously that EU4 states may not match V2 states.

**Comment by Zemurin** [comment]
This is fixed, can close.
