### ISSUE TITLE
Women Monarch Portraits in conjuction with dynasty names from eu4

### ISSUE THREAD

**Issue by WilhelmStein** [ParadoxGameConverters/EU4toVic2#123]
Title says it all. It would be nice to be able to have women monarchs, (especially being able to keep an immortal ruler from ck2/eu4 :) ), as referenced in here #433 . Quite misc but more flavor is always a welcome addition in my book.

**Comment by IohannesIohannium** [comment]
Vic2 doesn't name neither picture Heads of States, this issue is thus to be closed

**Comment by WilhelmStein** [comment]
I never said it did, the title states that this would be something to be carried over through eu4 metadata.
