### ISSUE TITLE
1.0Ha sub-release not supporting multiple mappings

### ISSUE THREAD

**Issue by IohannesIohannium** [ParadoxGameConverters/EU4toVic2#139]
The 1.0Ha sub-release doesn't correctly read the country mappings and, in instances where they would be more than one country mapped, only the last one is read.

E.g.:
```
link = { eu4 = TUR v2 = TUR } # Ottomans
link = { eu4 = k_ottoman v2 = TUR } # Ottomans
link = { eu4 = k_anatolia v2 = TUR } # Anatolia => Turkey
```

The converter will completely discard the first two lines and generate a new country for the EU4 "TUR", assigning them a random flag, as same thing happens also, I guess, with CK2 name-to-tile file.

**Comment by Zemurin** [comment]
Ck2 exports ottomans as shit:
![otto2](https://user-images.githubusercontent.com/2392697/71212476-b043a380-22b1-11ea-9fbe-a2befe823844.png)

They know it's TUR, but the exported spits out a random country with ottoman_government. Resulting conversions are what they are.

However, coming from EU4, continuity is preserved:
![otto](https://user-images.githubusercontent.com/2392697/71212542-d6694380-22b1-11ea-83fb-f9714cc4f4e1.png)

As for the bookmark, it now floats, so this issue can probably be closed?
