### ISSUE TITLE
Religious-regional cultures not working

### ISSUE THREAD

**Issue by IohannesIohannium** [ParadoxGameConverters/EU4toVic2#142]
It seems as the converter doesn't care about the various lines in the culture mapping file that teaches it to, e.g. make the Muslim Serbians Bosnjaks or remembering that British people in Canada are "Anglo Canadian".

I don't know if it may be tied with order as in #507, but in doubt, I post it here, as it is an annoying bug and may cause cultural-core problems.

**Comment by Idhrendur** [comment]
Ah! I'd say that's still a bug, but helps pin down why it happens.

**Comment by IohannesIohannium** [comment]
This issue is related to #47

**Comment by Idhrendur** [comment]
They look connected, but really are separate from a programming perspective.
