### ISSUE TITLE
Problem With Country Names

### ISSUE THREAD

**Issue by GhostFlesh** [ParadoxGameConverters/EU4toVic2#143]
There is problem with Country names.
Example, It says X34 instead of Jamtland
It says Y46 instead of Tangier. Is there any solution for this?
And the eu4. save is converted from CK2.

Game Version: 1.24.1.0

**Comment by Idhrendur** [comment]
Should be fixed by #240

**Comment by IohannesIohannium** [comment]
Same issue as #153
