### ISSUE TITLE
1.27 and 1.28 update

### ISSUE THREAD

**Issue by IohannesIohannium** [ParadoxGameConverters/EU4toVic2#151]
As with every EU4 patch, an update to the converter will be needed. After #517 is merged, I'll take care of doing the needed updates, this time using a new policy of splitting it in various littler parts as I was requested to.

The 1.27 patch adds the countries of _Ilkhanate_ (already in due to CK2), _Kalmykia_, the _Mongol Empire_ (already mapped to Vic2 MGL due to CK2), and the _Synthetics_ (interesting easter egg, [EDIT] I'll make them map to Alien Invaders), no new culture or religion, and an unprecisated number of new province mappings needed, but easy to take care of.

**Comment by IohannesIohannium** [comment]
Solved in pulls #156 to #164

**Comment by Khorps** [comment]
Is a version of the converter for EU4 1.26 available for download or is it still in approval?
