### ISSUE TITLE
Revolutionary Tricolors

### ISSUE THREAD

**Issue by IohannesIohannium** [ParadoxGameConverters/EU4toVic2#167]
The converter happens to convert revolutionary tricolors to a full-white flag.

**Comment by Zemurin** [comment]
![flag](https://user-images.githubusercontent.com/2392697/71423986-c70d4000-268d-11ea-95d1-40e23a45d0cd.png)

The dharmatized build doesn't translate the revolution at all (though it does boost liberals and guillotine reactionaries from upper house). Dharma status for revolutionary France is in fact a simple feudal monarchy, which is something PDX should probably solve internally.

We should override this manually of course.
