### ISSUE TITLE
Exe file not in release zip

### ISSUE THREAD

**Issue by Starmann** [ParadoxGameConverters/EU4toVic2#186]
I'm probably really fucking stupid but the (release links)[https://github.com/ParadoxGameConverters/EU4toVic2/releases/download/windows_development_build/EU4ToVic2.zip] don't actually have the EU4toV2converter exe, making the whole developer beta kinda pointless.

**Comment by Idhrendur** [comment]
Sorry about that, it's an ongoing problem I haven't figured out yet. :-(

**Comment by Starmann** [comment]
How are you making the Zip file?

**Comment by Idhrendur** [comment]
It's all [automated on Appveyor](https://ci.appveyor.com/project/Idhrendur/eu4tovic2). So I'm not able to directly see what it's doing.

**Comment by Starmann** [comment]
Would you mind terribly manually compiling me an .exe as Visual Studio tends to bug out on my machine?

**Comment by Idhrendur** [comment]
I did you one better and fixed the automated build.
