### ISSUE TITLE
converterUnions.txt reverted changes

### ISSUE THREAD

**Issue by Idhrendur** [ParadoxGameConverters/EU4toVic2#224]
EU4toV2/Data_Files/blankMod/output/decisions/converterUnions.txt had some elements with the wrong number of braces, breaking other decisions. They've been removed, but should be rewritten as needed and put back.

See commit 2863717781b6e4999c81695e111f684d7f3d16a8 for reference.

**Comment by Idhrendur** [comment]
@IohannesIohannium It won't let me just assign it to you, but you're the one who understands what those lines were supposed to do.

**Comment by IohannesIohannium** [comment]
I'll look at it as soon as I can

**Comment by IohannesIohannium** [comment]
Solved in #225

**Comment by Idhrendur** [comment]
Thanks! I tested and it was great, so it's now merged.
