### ISSUE TITLE
Extra cores being added when they shouldn't

### ISSUE THREAD

**Issue by Idhrendur** [ParadoxGameConverters/EU4toVic2#231]
This is persisting even after unions.txt is cleared.

See [this forum post ](https://forum.paradoxplaza.com/forum/index.php?threads/eu4-to-vic2-converter-release-thread.973026/page-151#post-25671396)for mod and save.

**Comment by IohannesIohannium** [comment]
What countries got extra cores added (I can't read the forums)? The Taiping-n-CSA decision may be at fault for this

**Comment by Idhrendur** [comment]
It's some of the same stuff Inspecta had been mentioning on the Discord. I can't recall if we addressed it or answered the question.

**Comment by Zemurin** [comment]
I had the same experience recently, forum post here:
[Forum Post](https://forum.paradoxplaza.com/forum/index.php?threads/eu4-to-vic2-converter-release-thread.973026/page-170#post-25932953)

**Comment by IohannesIohannium** [comment]
What do you mean by "major issues"?

**Comment by Zemurin** [comment]
Mainly revanchism at 43% from the game start for not owning provinces I never owned in either CK2 or EU4. Trouble is other nations also have these issues causing constant wars (0 infamy for own cores, right).

**Comment by Idhrendur** [comment]
Are you experiencing this even with unions.txt cleared out?
