### ISSUE TITLE
Duplicate line in country history

### ISSUE THREAD

**Issue by Idhrendur** [ParadoxGameConverters/EU4toVic2#235]
See this forum post for more detail:
https://forum.paradoxplaza.com/forum/index.php?threads/eu4-to-vic2-converter-release-thread.973026/page-156#post-25719095

**Comment by IhateTrains** [comment]
The user didn't attach a save in that post. Does anyone have a have with the same problem?

**Comment by Idhrendur** [comment]
Eh, closing until someone reports again.
