### ISSUE TITLE
Error in converter decisions

### ISSUE THREAD

**Issue by Idhrendur** [ParadoxGameConverters/EU4toVic2#236]
"I found an error after conversion in “converterDecisions.txt”. In “form_malaya” before “effect =” line there is one more “}” than is needed."

**Comment by IohannesIohannium** [comment]
There is no file named `converterDecisions.txt`, it's `converterUnions.txt` who has the `form_malaya`. Even so, I found no extra curly bracket in it.

**Comment by Idhrendur** [comment]
Huh. Okay, closing.
