### ISSUE TITLE
Post-colonial event bug

### ISSUE THREAD

**Issue by Idhrendur** [ParadoxGameConverters/EU4toVic2#238]
"For some reason when I converted the USA I get an event 2 years in that removes Yankee as primary and sets it to afro American. This kills my country. How do I fix this?

Edit: It would seem that because my capital Washington is mostly slaves it sets the culture to that."

"Huh. I'll have to ponder that one a bit. I'm not familiar with the event, but it sounds like something that's trying to handle post-colonial stuff."

"It is. It's the post colonial event for ensuring colonies have a primary culture. It's the language of the bureaucracy event and only has one option and that's "amen". This sets your primary culture to the majority culture in the capital, which in Washington D.C.s case was African slaves. Having a primary culture that's entirely enslaved with the slavery debate modifier was bad. I reconverted with New York as my capital and everything was fine(except my entire country joining the confederacy was that's a different issue)."

**Comment by IohannesIohannium** [comment]
Solved by #277

**Comment by Zemurin** [comment]
Can close.
