### ISSUE TITLE
problem when reading CK2 Exports

### ISSUE THREAD

**Issue by Nyarukocqc** [ParadoxGameConverters/EU4toVic2#239]
i found an issue while converting.
The converter is currently unable to read converted_countries_l_english.yml files from eu4_export.
This file placed in the Converted_Country1444_11_11\localisation\replace folder by default.
But the converter only read localisation files outside of the replace folder.
So,if you convert a save that included nations generated by ck2,it will be "Y30" "Y40" "X20".
If i moved converted_countries_l_english.yml file outside of replace folder,the problem will be fixed.

**Comment by IohannesIohannium** [comment]
Same issue as in #153

**Comment by Idhrendur** [comment]
And thus also should have been fixed by #240
