### ISSUE TITLE
Compressed Saves are not supported !

### ISSUE THREAD

**Issue by YuseinST** [ParadoxGameConverters/EU4toVic2#242]
![Adsız](https://user-images.githubusercontent.com/50953521/63224899-9004ba80-c1d3-11e9-95d6-9783f8eecc4b.jpg)
l am taking that issue when l was converting why is that?

**Comment by Idhrendur** [comment]
Paradox changed the compressed save format so that the save is split into three files. To support that would require a very large amount of work, and so it's just unfeasible.
