### ISSUE TITLE
Clean up province weight determination

### ISSUE THREAD

**Issue by Idhrendur** [ParadoxGameConverters/EU4toVic2#243]
The code to find the province weight for pop conversion is messy. Clean it up.

**Comment by Clonefusion** [comment]
https://pastebin.com/dbriiQnu
Things not in pop conversion atm.
2. and 3. are functions to check for prov modifiers in provinces.
4. is a function to check if a province is a territory in eu4
1. and 5. implements a list of prov modifiers to work in the conversion

**Comment by Clonefusion** [comment]
ledger={
			income={
				708.636 898.606 644.154 47.753 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 
			}
Third value 644.154 is the trade income of a nation and if divided by number of provs for each nation could be added as value to represent traders bringing money to the country.

**Comment by Zemurin** [comment]
Solved, can close.
