### ISSUE TITLE
Compressed save issues

### ISSUE THREAD

**Issue by Idhrendur** [ParadoxGameConverters/EU4toVic2#245]
According to a report on reddit, if a save has ever been compressed, even future uncompressed versions are unlikely to work. This may give hints as to other problems.

https://www.reddit.com/r/paradoxplaza/comments/cvxkew/eu4_to_vic2_converter_sometimes_working/

**Comment by IohannesIohannium** [comment]
EU4 compressed save games can be manually uncompressed: turn the save into a .zip file and then, extracting it, you can find the actual save in it, which is called `gamestate` (without extension). The only important thing missing from this file is the date of the save, which is in the neighbouring `meta` (no extension) file.

While an uncompressed save (opened as if it were a text file) starts with always `EU4txt`, a compressed one will always start with `PK`

There could be this message if the converter reads the file starts with `PK`: "This savefile is compressed. Please, uncompress it before trying to convert"

**Comment by Idhrendur** [comment]
Yep, which the frontend does. This report was that if you had a compressed save, then in EU4 saved again with it uncompressed, it still wouldn't convert. But I've seen contrary evidence since then, so I'll close this out.
