### ISSUE TITLE
New revolting nations have noculture

### ISSUE THREAD

**Issue by Idhrendur** [ParadoxGameConverters/EU4toVic2#248]
Reported here:
https://forum.paradoxplaza.com/forum/index.php?threads/eu4-to-vic2-converter-release-thread.973026/page-160#post-25766195

**Comment by IohannesIohannium** [comment]
That's not intended. Could you show me the forum message, since I don't have access to it?

**Comment by Idhrendur** [comment]
There's not a lot more detail, but here's the post:

"hey i have a new issue that has cropped up in the mod. when a nation revolts from its overlord and the overlord chooses to fight, the new nation has noculture as its primary. happens randomly with different nations. one nation i saw had all the correct cultures and the other had secondary but no primary culture. is this a known bug?"

**Comment by IohannesIohannium** [comment]
Oh, yeah, I had forgotten to add a fix to that. It is now part of pull #277
