### ISSUE TITLE
Odd culture conversion for CK2 exports

### ISSUE THREAD

**Issue by MaxTheDesertManIran** [ParadoxGameConverters/EU4toVic2#253]
Several cultures that have never existed in EU4 are predominant in several regions in Victoria, for example the majority of Anatolia is Turkish while the Turkish culture has never touched Anatolia in neither EU4 nor CK2. Another example is English/Irish/Welsh cultures being the majority in regions that have been Norse since the 800s lore-wise. The "original culture" of these provinces in CK2's exported mod is Norse, which is why I believe this issue is caused by the converter using the vanilla "original culture"s of provinces to determine culture ratios in pops, instead of the ones in the mod.
![x](https://user-images.githubusercontent.com/34010166/64804912-1cbd5100-d5a5-11e9-81ce-e054297690e5.png)

**Comment by MaxTheDesertManIran** [comment]
It has fixed the issue for the most part, however there still are some provinces that have the default original culture and religions used for them. I'm currently checking to see what's different in the EU4 files of these specific provinces.

**Comment by MaxTheDesertManIran** [comment]
Ah, oddly the pockets that aren't correctly converted are the exact pockets that were correctly converted before.
![weirdly](https://user-images.githubusercontent.com/34010166/64883223-1ea21580-d674-11e9-8b3c-30d3b152a3ab.png)

**Comment by MaxTheDesertManIran** [comment]
I think I've found the issue. The EU4 default culture and religion load first, and the ones from them mod second, in the savegame for the provinces that are correctly converted.
But the exact opposite is happening in the ones that are converted incorrectly.
![11](https://user-images.githubusercontent.com/34010166/64883920-aa687180-d675-11e9-94ca-321fdcfece3a.PNG)
![22](https://user-images.githubusercontent.com/34010166/64883922-aa687180-d675-11e9-9fa8-8b25b69e205e.PNG)

**Comment by Idhrendur** [comment]
Drat, I had assumed a consistent order. Back to the drawing board.

**Comment by Idhrendur** [comment]
Okay, I've tried another fix that I think should sort it. Please try that out.

**Comment by MaxTheDesertManIran** [comment]
The issue still persists, these provinces are treated as if they were converted in 1444.

**Comment by Idhrendur** [comment]
I had the logic backwards, doh! Mind testing again?

**Comment by MaxTheDesertManIran** [comment]
Yep, the issue's gone!

**Comment by Idhrendur** [comment]
Oh thank goodness, the next thing to try would have been a ton of effort.
