### ISSUE TITLE
Culture mapping updates

### ISSUE THREAD

**Issue by Idhrendur** [ParadoxGameConverters/EU4toVic2#256]
1.29 has added manchu_new and evenk. They need mapping to Vic2 cultures (and if necessary, new VIc2 cultures added).

**Comment by IohannesIohannium** [comment]
Solved by #264

**Comment by Idhrendur** [comment]
Okay, just waiting for the testers to show up again and double-check things.

**Comment by Zemurin** [comment]
Converter will again protest, quite loudly and in different tones, if a culture or religion is missing somewhere or cannot be converted into something else. Since it doesn't do any of that on test saves, everything from eu4 1.29.4 is mapped properly.
