### ISSUE TITLE
Mod crashes on load in Vic2

### ISSUE THREAD

**Issue by Idhrendur** [ParadoxGameConverters/EU4toVic2#267]
Uploaded here: https://forum.paradoxplaza.com/forum/index.php?threads/eu4-to-vic2-converter-release-thread.973026/page-165#post-25838195

**Comment by Zemurin** [comment]
The link is for a wrong issue, that particular save game fails to convert because converter attempts to use 1.29 mappings over 1.28 save. Investigating.

**Comment by Zemurin** [comment]
Whatever it was, it no longer crashes, can close issue:

![fixed](https://user-images.githubusercontent.com/2392697/71168484-1cdd8480-2257-11ea-843c-8936fabde058.png)
