### ISSUE TITLE
Decision: vassal_CRB

### ISSUE THREAD

**Issue by Zemurin** [ParadoxGameConverters/EU4toVic2#278]
vassal_CRB decision is broken, doesn't secede carribean but grants prestige, causing owner +10 prestige every day.
[Forum post](https://forum.paradoxplaza.com/forum/index.php?threads/eu4-to-vic2-converter-release-thread.973026/page-170#post-25940400)

**Comment by IohannesIohannium** [comment]
On my machine, the decision works correctly

**Comment by Zemurin** [comment]
In my game almost entire Caribean was under Haiti, which England (not GRB) had sphered (not satelite). They were able to use this decision daily, seceding nothing as it was already a secondary power.

**Comment by IohannesIohannium** [comment]
Sadly I'm unable to find a solution that works to such a problem. Province seceeding is not only regulated by ID, but also by country scope as well, and it is impossible to do a *any owned province with X id* scope inside *any vassal of Y* scope

**Comment by Zemurin** [comment]
I think the decision should check only against owned provinces, not sphered country's. What happens is a sphered country owns all of it (common coming from EU4, since it'd be the same culture and a likely target for sphering), so secede kicks off, and nothing happens as the overlord owns nothing (aside for +10 prestige).
