### ISSUE TITLE
Decision: Postcolonization issues

### ISSUE THREAD

**Issue by Zemurin** [ParadoxGameConverters/EU4toVic2#279]
[Forum Post](https://forum.paradoxplaza.com/forum/index.php?threads/eu4-to-vic2-converter-release-thread.973026/page-170#post-25932910)

In essence, postcolonization is good because it guides north american countries to assume something of a proper shape, but causes major issues in africa - countries there form and secede before their respective regions are even colonized fully, causing bordergore and allowing the player to (for example) lose a single kongo state on secession but then colonize and keep the rest.

Postcolonization in Africa must be moved post 1900, once it's complete.

Another example where it affects europe, with coutries like LIP seceding for no good reason. On CK2 games where there is no Germany (and may not be any german culture) having LIP declare independence is silly.

**Comment by IohannesIohannium** [comment]
The postcol decisions are at player's discretion. It's up to them to decide when should Africa be split up.

**Comment by Zemurin** [comment]
Fully agree. However, the North America part of the postcol decision is what shapes USA, Canada etc towards historical form, and enabling that post 1900s makes little difference (too late). Is there any chance to separate these by continents - the american ones into Manifest Destiny decision ideally selectable early, dropping european and leaving only africa in postcol to be used post 1900s?

**Comment by IohannesIohannium** [comment]
The Americas decision is the one at game start, allowed to be chosen only until you reach 1837. By choosing it, the player says they are not against some historical railroading.

The Africa decision is separate, available since 1880s to game end, but you aren't given the option if you refuse the Americas one.

There's no "European" postcol decision. You may be thinking about the event that redistributes some Middle Eastern cores (Cyprus, Crete, Palestine, etc.). It is needed because otherwise Iraq would lay cores on all of Northern Arabia

**Comment by Zemurin** [comment]
Ahah, found the bug then, probably. American decision sets der_postcolonialism flag. 
In events/postcolonial.txt Congo for example checks for this flag and then secedes immediately in 1826. It should be checking for der_postcolonialism2 flag which is set by the second decision. Same goes for South Africa, Oranje etc.

To be perfectly hones, I've ran about 10? 15? megacampaigns in the last year and not once had I ever seen the second decision making me wonder does it even show up? This is the first I've seen it and only by checking the files, huh.

**Comment by Zemurin** [comment]
Closing issue as this was addressed already by @IohannesIohannium.
