### ISSUE TITLE
Bug: Canals are no longer being recognized as built

### ISSUE THREAD

**Issue by Zemurin** [ParadoxGameConverters/EU4toVic2#285]
Canals exist in EU4 but are not applied to vic2. Attaching Panama province from savegame.
[835.txt](https://github.com/ParadoxGameConverters/EU4toVic2/files/3818457/835.txt)

**Comment by Idhrendur** [comment]
Could you also attack a full save for the sake of testing?

**Comment by IhateTrains** [comment]
This is the issue I was supposed to make. They seem to be properly read in the EU4 save but are not converted to Vicky decisions.

**Comment by Zemurin** [comment]
I'm attaching my save but it requires 1356 mod to load in EU4. For purposes of testing the converter it should work even if you dump the mods_enabled from the save.

[United_States1806_01_12.zip](https://github.com/ParadoxGameConverters/EU4toVic2/files/3820702/United_States1806_01_12.zip)

**Comment by Zemurin** [comment]
Fixed in #318.
