### ISSUE TITLE
Gameplay/bug: Territorial cores are accepted as stated.

### ISSUE THREAD

**Issue by Zemurin** [ParadoxGameConverters/EU4toVic2#295]
-668={
		name="Macau"
		territorial_core="CAS"
		owner="CAS"
		controller="CAS"
		cores={
			YUE CAS 
		} 
...
}

If a province is a territorial core it must not:
a) transfer the core on conversion
b) be a full state

Fixing first is easy, look for territorial_core=".." and if found don't apply the core to the province.
Fixing second requires going into that same province and applying colonial flag:

Onto the province as is:
history\provinces\china\1498 - Macao.txt
owner=CST
controller=CST
add_core=CST    <-- dump this!
add_core=YUE
trade_goods = tea
life_rating = 32

add:
territorial=2

And that's it. Unless this is done, whomever owns china (or india, or similar) instantly owns millions of pops, being able to field hundreds of units in 1821.

**Comment by Idhrendur** [comment]
Fixed by #316
