### ISSUE TITLE
Gameplay: HRE cores should be removed by default

### ISSUE THREAD

**Issue by Zemurin** [ParadoxGameConverters/EU4toVic2#298]
Unless HRE exists, its cores should be removed on conversion. What happens fairly regularly is that one german minor attacks another and releases HRE as a separate nation, and this can happen anywhere within the HRE region. The resulting minor (a few provinces/single state) then owns "cores" on the entire ex-hre region, which is fairly silly and can, not often, cause additional silliness with unification.

![hre](https://user-images.githubusercontent.com/2392697/69675829-dc4b7a80-109f-11ea-99b7-b3598f6f9dda.png)

**Comment by IohannesIohannium** [comment]
As said on Github, the method to adopt here is not to remove the HRE at all (cores will disappear when liberal revolution kicks in anyway), but to make the released HRE be annexed by the current Emperor in such instances through an event

**Comment by Idhrendur** [comment]
Either do this as a one-off special case for HRE.

Or better yet (as requested), have a data file that lists all countries that should have "is_releasable_vassal = no" and add it to all of them.
