### ISSUE TITLE
Create Vic2 culture file instead of copying an existing one

### ISSUE THREAD

**Issue by Idhrendur** [ParadoxGameConverters/EU4toVic2#30]
Instead of simply copying a pre-built vic2 cultures file, create a new one during conversion (though the old one can be used as a base to start from). This will enable the ability to create several other features, as well as making missing culture mappings less of an issue.

**Comment by Idhrendur** [comment]
Probably a good start is just reading the existing Vic2 one and outputting it again. If we have additions or edits to it, they can then go in a simpler file we also read.

**Comment by Zemurin** [comment]
Proposal for complete rework:

1. Ignore vicky2 and blankmod cultures.txt, and pull culture definitions (union, names, etc) from eu4 and ck2/othermod conversion sources
2. read culture_merge.txt that would define identical parent cultures (link= {saxon bavarian}), so all of these would merge into same eu4 source.
3. Roll through eu4 superregions and write down all starting cultures within the region - these are native eu4 cultures
4. for any non-native source culture, generate successor eu4 culture witin the superregion based on the culture group (new-germanic, new-hispanic, new-scandinavian)
5. Only now consult culture_map to see if we have actual name for the resulting culture and find out that new-hispanic in central america is in fact Vic2 "mexican", and convert all these new cultures.
5a. If there is no mapping assign a superregion-name (southafrican-germanic)
5b. Use culture definitions from source culture - mexican would use castillian names if source is castille.
5c. if there is a collision (portugal and castille both colonized central america), merge names - so both portugese and castillian would map into mexican and use both names as sources.
6. Convert all base cultures per culture_map and perform other splitoffs like icelandic, as defined in the file
7. Generate collective cultures.txt with all new newly-generated cultures within respective culture groups (hispanic now contains mexican and others)
8. Assign national cores according to individual culture - if we have a mapping defined in nationals.txt (link = { tag = MEX culture = mexican })
9. when distributing pan-nationalist cores ignore all provinces with new-cultures, they are not necessary to form anything.

**Comment by Zemurin** [comment]
Implemented.
