### ISSUE TITLE
Fix: Vic2 ignores the first line of localization files

### ISSUE THREAD

**Issue by Zemurin** [ParadoxGameConverters/EU4toVic2#306]
It expects the first line to be:
KEY;ENGLISH;FRENCH;GERMAN;POLISH;SPANISH;ITALIAN;HUNGARIAN;CZECH;HUNGARIAN;DUTCH;PORTUGUESE;RUSSIAN;FINNISH;X

And ignores it. Thus, for example, if you swap government names around in 1.29.csv, and put democracy first:
democracy;Constitutional Republic;République Constitutionelle;Konstitutionelle Republik;;República Constitucional;;;;;;;;;;;;;x;;;

![demo](https://user-images.githubusercontent.com/2392697/69926618-65eeb400-14b5-11ea-838e-835ab0b55ef2.png)

...it will be ignored and the country will revert to vanilla localization, ie. "Democracy". 

It affects only a handful of keys but is trivially fixed, just copy paste the KEY line at the beginning of each file.

**Comment by IohannesIohannium** [comment]
Oh, 1.29.csv was actually included in? My bad, it slipped in. Nevertheless, I'll take care of this issue.
