### ISSUE TITLE
"Map Properly Initialised" Error and Solution

### ISSUE THREAD

**Issue by Snipahar** [ParadoxGameConverters/EU4toVic2#314]
Sometimes Victoria II freezes on the loading screen when it says "Map Properly Initialised..." Below is how the problem can be fixed on the user's end.

(1) Open the "0_Names.csv" file. This can be opened as a .txt file if you do not have a .csv-compatible program. This should be in a directory similar to this one:

C:\Program Files (x86)\Steam\steamapps\common\Victoria 2\mod\YourSaveFileName\localisation

(2) Find "PHA;U;Ü;Ü;;U;;;;;;;;;x" without quotes.

(3) Replace it with "PHA;Uu;Üu;Üu;;Uu;;;;;;;;;x" without quotes.

I saw this solution posted by Zemurin in the Paradox forums. I have had several people with this error on the Steam Workshop pages and this solution seemed to work.

**Comment by Idhrendur** [comment]
Actually, good news, I fixed it just yesterday! It shouldn't affect people any more. #305

**Comment by Snipahar** [comment]
Ah, that's great! I must have just missed that previous thread!
