### ISSUE TITLE
Recombine some cultures on conversion

### ISSUE THREAD

**Issue by Idhrendur** [ParadoxGameConverters/EU4toVic2#35]
Once [this issue](https://github.com/ParadoxGameConverters/EU4toVic2/issues/33) has been done, some cultures can be recombined into singular cultures to resolve [these types of problems](https://forum.paradoxplaza.com/forum/index.php?threads/the-eu4-to-v2-converter-project.707362/page-177#post-20566491).

**Comment by Idhrendur** [comment]
In summary - adjust the creation of dynamic cultures to account for multiple cultures from the parent culture group in the region. Ensure they all become one resulting culture.

**Comment by Zemurin** [comment]
This is implemented indirectly. 

###Colonies
All cultures from a shared culture group will (unless overridden via culture_map.txt) mutate into the same culturegroup_superregionname_culture for colonies and be combined there.

For different culture sources (ck2, mods), we're merging their cultures within culture_group definition in cultures.txt, so one can have both EU4's "venetian" and CK2's "italian" inside the culture group mapping into vic2's italian target, which in turn will transform into "italoamericano" in colonies.

###Non-Colonies
Every base eu4 culture (no matter the source, like ck2) must nave a corresponding culture_map entry anyway, so they will recombine there as well.
