### ISSUE TITLE
Tweak number of industrial pops

### ISSUE THREAD

**Issue by Zemurin** [ParadoxGameConverters/EU4toVic2#365]
[See here.](https://forum.paradoxplaza.com/forum/index.php?threads/eu4-to-vic2-converter-release-thread.973026/page-183#post-26170889)

Extend factory-benefiters to 15, boost craftsmen by 3, and clerks by 2.

**Comment by Idhrendur** [comment]
By my [redone math](https://forum.paradoxplaza.com/forum/index.php?threads/the-eu4-to-v2-converter-development-thread-not-for-troubleshooting.707362/page-255#post-26171196), there should be 493 clerks per factory (instead of 181) and 8170 craftsmen per factory instead of 2639.
