### ISSUE TITLE
EU4 directory not recognized in Linux

### ISSUE THREAD

**Issue by Dorumagaxs** [ParadoxGameConverters/EU4toVic2#388]
The Linux version of the converter expects a file named "eu4.exe" in the Europa Universalis IV installation folder. But in the Linux install the file is named "eu4". Simply creating a link file named "eu4.exe" already solves the problem, but for the sake of compatibility maybe it could be corrected in the converter.

**Comment by Zemurin** [comment]
implemented a fix.
