### ISSUE TITLE
Accepted cultures rework #419 Option for both methods?

### ISSUE THREAD

**Issue by oliver1706** [ParadoxGameConverters/EU4toVic2#556]
Hi everyone, love all the work you've done, it's extremely impressive. Feel free to delete this if I'm in the wrong place, but I wanted to ask whether it'd be possible to have the option to instead use the old system of determining accepted cultures, as was removed [here](https://github.com/ParadoxGameConverters/EU4toVic2/pull/419)? For people who do wish to use the new system, it'd also be nice to be able to modify the fifteen percent threshold. I'd mainly find this feature useful for manually changing via console countries in different tags to fit the narrative desired. Thanks!

**Comment by Zemurin** [comment]
We cannot go back to the old system, it was discarded for gameplay reasons as it didn't make sense. However pulling the percentages out into a config file is quite possible.

**Comment by oliver1706** [comment]
I wouldn't suggest going back to the old system entirely, I understand the logic behind the change, it's just be nice to give the user the choice between the two. IMO, it hamstrings some of the key gameplay mechanics of Victoria 2, as all sufficiently large minorities will be accepted. This means historical Austria will immediately accept Hungarians for example. While it might be the case that they would have done this already in EU4, the player can use a mod to prevent or make accepting cultures more difficult.
As another example, I just converted a save then and Lithuania (with effectively 1444 borders) ends up with Byelorussian, Ukrainian and Russian accepted, basically destroying all chance of interesting (and IMO realistic) nationalist conflicts there.
I'm not familiar with C++, but I am willing to look into doing this myself if you'd like.

**Comment by Zemurin** [comment]
Well, with options out in a config file you could set threshold for accepting a culture to 0.5 or higher to prevent such issues.
Our problem was not with too few accepted cultures but with too many - where nations had 5-10 accepted cultures making the issue much worse.

**Comment by oliver1706** [comment]
Yeah I agree, EU4 accepting culture mechanic is broken and just plain silly. Perhaps there could be an option for the first X accepted cultures to be transferred over, or first X over a certain percentage threshold of development? This could even potentially be limited further by religion or culture groups.

**Comment by Zemurin** [comment]
We cannot operate on EU4 cultures in this fashion. Multiple eu4 ones map to single vic2 one for example, and you cannot order the cultures you accept. Development is also not useful, we use it as a modifier for vanilla vic2 populations, not an absolute value. A 100dev grenland will still have a few k pops. Overall the only thing we truly can rely upon are vic2 pops and their culture, religion and westernization status. And we've used all of those to the best of our ability, thus the current system.

**Comment by oliver1706** [comment]
Alright fair enough, the mapping thing does make it complex. The ability to raise the thresholds would alleviate a lot of this, so that would be great to have. What could also be interesting is having the wrong religion pops count for less in accepting. For example, when Lithuania is checking if Russians are over 20% of their population, they might find they make up 30%. However, two thirds of those Russians are orthodox, so they only count for .25, giving 10% + 20%*.25 = 15%. Food for thought. Anyway, thanks for your time, and thank you to your and the team for all the hard work you've done! Have a good one.
