### ISSUE TITLE
south america cultures

### ISSUE THREAD

**Issue by Zemurin** [ParadoxGameConverters/EU4toVic2#577]
--

I don't think that south andean culture should be the region of upper peru, maybe make it so that it is split by area instead?
the Tucuman areas and the Chaco areas should be platinean.

Also, the Northern Chile, Central Chile, and Southern Chile areas should be south andean, since the chilean culture is different than la plata "argentina and uruguay."
This would make it match up more to vanilla and hpm culture mappings as well.

If you don't agree with this change, how would i change it so that it would be like how I mentioned?

Please take this into consideration.

--

**Comment by IohannesIohannium** [comment]
The Latin American culture splits should be based on vanilla

**Comment by Zemurin** [comment]
done via #579
