### ISSUE TITLE
Infinite loop between Naples and two sicilies

### ISSUE THREAD

**Issue by Thinking-waffle** [ParadoxGameConverters/EU4toVic2#652]
Because the decision to form the 2 siciles doesn't transfer land, if you are Naples (should also be possible with Sicily regarding the owner of the city of Naples) and have Palermo in your sphere you can form the 2 siciles but then later you will get the event saying that you don't have Palermo so you will revert to Naples again.

To test: be Naples (or Sicily)
Own Naples (the city) (or palermo)
Don't own Palermo (or naples) but have its owner in your sphere
form the kingdom of 2 siciles and wait.
you should revert to Naples (or Sicily) after a while getting free prestige and being able to restart the cycle.

**Comment by Thinking-waffle** [comment]
To add: the event in question is '452020' but the other similar events in dissolutionKUK are probably similarly faulty.

**Comment by IohannesIohannium** [comment]
Solved by #669
