### ISSUE TITLE
Spain created by Portugal enters as an event repeating in VIC 2

### ISSUE THREAD

**Issue by Thinking-waffle** [ParadoxGameConverters/EU4toVic2#653]
Due to some peculiar inheritence back in CK2, Portugal took over Castille and therefore became Portuguese Castille -> Spain in EU4

In VIC2 there is an event to ensure the acceptance of Spanish cultures but it's not written for a Portuguese Spain so it triggers every month or so

The event responsible should be "601019" but the neighboring similar events are worth a look too.

**Comment by IohannesIohannium** [comment]
Solved by #669
