### ISSUE TITLE
Unification decisions grant cores on what you have, not on each cores assimilated.

### ISSUE THREAD

**Issue by Thinking-waffle** [ParadoxGameConverters/EU4toVic2#654]
it isn't a problem when you just annex/sphere a country and then assimilate it while forming a union like scandinavia. But if said country had other cores and if you unlocked that decision by sphering countries with such cores but not of that culture (and therefore not annexed) you will not get that land and will not receive cores on it.

In my game I had to sphere Genoa to unlock the decision. It gave me cores on Persian and Greek land I owned but not on Georgian cores owned by Genoa

Is this working as designed?

**Comment by Zemurin** [comment]
More generally:

Any formable decision must ensure one retains cores on all (currently) owned land + all cores owned by anyone being annexed.
This is a decision issue and decisions need to be patched - both the generic one and all named ones, if needed.

**Comment by Zemurin** [comment]
Fixed with #757
