### ISSUE TITLE
South Africa and primary culture

### ISSUE THREAD

**Issue by Zemurin** [ParadoxGameConverters/EU4toVic2#661]
Is it possible to make it so that South Africa doesn't have Anglo-African as its primary culture even though Britain never colonized South Africa?

> South africa, if it existed at conversion time, will have that primary culture that it had in EU4. If it was released during vic2, then it'll probably default to vanilla files.

Seems like the convertor switches it's vanilla culture of British to the South African neoculture from British ("Anglo-African"). I kinda wish that there would be some sort of event or decision at game start for whatever nation controls the region to change South Africa's culture/religion to the appropriate neoculture/religion (if South Africa doesn't already exist), but I have no real modding experience so I don't know how possible it is to do that. Sorry for focusing on this, I've noticed the AI tends to release them at the start of vic2 so it's been a bit of a pet peeve of mine.

**Comment by IohannesIohannium** [comment]
Solved by #669
