### ISSUE TITLE
Dynamic colonial nation map colours

### ISSUE THREAD

**Issue by Art2104** [ParadoxGameConverters/EU4toVic2#682]
IDK if I should post this here or on the forums, but I've noticed you have added a feature where the colours of the colonial nations(and all the nations in general) correspond to those in EUIV. The issue is, even if a colonial nation stops being a sattelite and leaves the sphere of a parent country, it still retains the same map hue(e.g. USA leaving the British Empire, but remaining bright red on the map, completely indistinguishable from the neighbouring british puppets). The question is, can it be either a)somehow integrated into the game via a decision or smth else to change the country's colour to its vanilla colour, if any is available(light blue for the US, Green for Brazil and so on), or b) if it is too hard to implement, at least have an option in the converter to retain vanilla colours for countries on the map where possible?

**Comment by Zemurin** [comment]
Neither is possible.

1. If a colonial nation is standalone (got its freedom in eu4), then it has a proper tag (USA, BRA) and retains vanilla vic2 colors, flag and all.
2. If a nation is standalone but didn't get a proper tag for whatever reason, so it still has the dynamic tag, we guesstimate which nation this may be and assign proper vanilla flag and colors.
3. If a nation is not independent then it's converted as C09 (for example) and we don't know which nation it is at all. There may be 3 USA-equivalents in the same eastern USA, by english, french and dutch, and neither of those is the USA. We cannot give any USA tag (and flag and colors) as it'd create a mess.
4. When a nation peacefully leaves sphere of inlfuence that's way past conversion point. What they will look like, where will capital be, and what will be its name or culture, flag or colors, is impossible to foresee. Thus we cannot create decisions that would tie that nation to a specific historical nation. You are free to change its name manually (in localisations) and set the colors yourself by editing its file.
