### ISSUE TITLE
Problem with Lithuania forming the united Baltic state

### ISSUE THREAD

**Issue by Thinking-waffle** [ParadoxGameConverters/EU4toVic2#767]
The converter provides decisions to unite the Baltic states, I thought that those were causing a problem.
But no the problem comes from the base game decision form_union_nation. I am certain of that because of the 45 prestige requirement.

Lithuania stayed independent through the whole of EU4 and is quite strong as it controls Belarus, a good chunk of Ukraine, western Russia, and the coast up to Danzig. But when it got the Livonian order and Denmark in its sphere it became the united Baltic states, without annexing Livonia or the bit of Estonia held by Denmark (because those don't have baltic as primary culture because Livonia has North German as primary culture).

After a while, the united baltic states get an event switching them back to Lithuania and they can transform again, farming prestige in the process.

![20210918145136_1](https://user-images.githubusercontent.com/26714269/133889978-b4d7ef43-5e35-4953-b8d2-cb16228c9cbb.jpg)

![20210918144942_1](https://user-images.githubusercontent.com/26714269/133889997-b74efe53-86f3-4321-9c33-b1b6574e0ae8.jpg)

**Comment by cetvrtak** [comment]
Should be simple enough to solve by adding "hpm_union = none" to Baltic group in configurables/culture_definitions.txt and account for that case when parsing cultures.
