### ISSUE TITLE
Culture switch aroo

### ISSUE THREAD

**Issue by WyattBurke** [ParadoxGameConverters/EU4toVic2#834]
So in my eu4 game I converted a lot of the world to jianzou ( starting Ming culture), it was transferred to Nanfaren, however, the primary culture category transferred to Naiyeren. 

also, I had like 13 accepted cultures when EU4  ended and now there are only three, I don't know if there's a cap for vic2 but it would be nice if you guys could do something to elevate this.

**Comment by WyattBurke** [comment]
also, I know this is out of the preview of the mod, but can add some of the EU4 console commands, it would make it easy to solve issues like this with /culture (desired culture) also /debug_mode.

**Comment by Zemurin** [comment]
> 

Go to forums, upload a save that demonstrates this. I need a reproducible case so I can fix this. Also upload your conversion's log.txt.

**Comment by Zemurin** [comment]
> also, I know this is out of the preview of the mod, but can add some of the EU4 console commands, it would make it easy to solve issues like this with /culture (desired culture) also /debug_mode.

How would we add console commands? And to what exactly?
