### ISSUE TITLE
Nations begin without enough factories to self sustain

### ISSUE THREAD

**Issue by Pactgo24518** [ParadoxGameConverters/EU4toVic2#904]
I'm undergoing a megacampaign that started at CK3. It was going well, until every time I use the converter, my nation doesn't have a factory for machine parts or any military equipment, meaning you have a finite amount of factories you can build, and no means of expanding your army.

There needs to be a way so all (apart from primitive) nations can have access to the bare essential trading materials so the game is playable. Currently there's no nation in the world to even trade the guns with, so I'm kind of in a jam.

Please update it so a few factories making machine parts and weapons are spawned at random or due to a certain factor, but the point is, these nations need the bare essential commodities to function properly.

**Comment by Zemurin** [comment]
Working as intended.
