### ISSUE TITLE
Culture conversion rates

### ISSUE THREAD

**Issue by IohannesIohannium** [ParadoxGameConverters/EU4toVic2#92]
Referring to previous issues (https://github.com/Idhrendur/paradoxGameConverters/issues/259 and https://github.com/Idhrendur/paradoxGameConverters/issues/146).

The culture conversion in EU4 should be reflected better in Vic2.

I think it should be based on the `assimilation_rate` of continents (Vic2 map file).

For example, an European province. Europe assimilation rate is -0.25. The result is that the primary culture will range from 0% (converted in 0 years) up to 25% (converted at least 100 years ago).

As another example, a North American province. Assimilation rate of 0.5. Primary culture ranging from 75% (0-year-old conversion) up to 100% (at least 100-year-old conversion).

This way, cultural cores in the New World will have sense.

If a province hasn't been culture converted, obviously, this means that it'll just get their primary culture at 100% wherever it is.

**Comment by Zemurin** [comment]
dupe of #47
