### ISSUE TITLE
Cultural questions

### ISSUE THREAD

**Issue by ViveleroyReal** [ParadoxGameConverters/EU4toVic2#959]
Hello, i am doing my own megacampaign with my discord and I wanted to know few things,

Is there a possibility to make alsatian culture from ck2 into the french culture? Or is it possible to seperate the north german culture and south german culture into smaller groups?

Also does the Bear culture converts to something else than natives culture.

Regards
Viveleroy

**Comment by Zemurin** [comment]
You have culture_map.txt in configurables so edit it as you wish.
Also, github issues are not a discussion forum. Please use the forum next time.
