### ISSUE TITLE
EU4 Peasant Republics converting to Absolute Monarchy in V2

### ISSUE THREAD

**Issue by BFKelleher** [ParadoxGameConverters/EU4toVic2#98]
Not sure how it's happening, but here's the history file of an early game Dithmarschen and the savefile
[DTT - Dithmarschen.txt](https://github.com/Idhrendur/paradoxGameConverters/files/1150675/DTT.-.Dithmarschen.txt)
[dithmarschen_1.zip](https://github.com/Idhrendur/paradoxGameConverters/files/1150677/dithmarschen_1.zip)

Edit: Version is 1.0G

**Comment by Zemurin** [comment]
No Dharma, 1.29.3 saves as:
```
government_name="german_republic" 
government={
			government="republic"
			reform_stack={
				reforms={
					"republic_mechanic"
					"peasants_republic_legacy"
				}
				history={
					"peasants_republic_legacy"
				}
			}
		} 
```
Dharma, 1.29.3 saves as:
```
government_name="german_republic" 
government={
			government="republic"
			reform_stack={
				reforms={
					"republic_mechanic"
					"peasants_republic"
				}
				history={
					"peasants_republic"
				}
			}
		} 

```
ie, identical.
Both convert as democracy for obvious reasons. 
Until we can differentiate governments though individual reforms (which are apparently saved regardless of Dharma being enabled) there is no method to convert DTT into a dictatorship.

I would close this issue, monarchy is definitely fixed.
